name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 159.223.71.240 >> ~/.ssh/known_hosts
          ssh root@159.223.71.240 "cd /var/www/html/megajx/live/webview/jx-app && git pull origin master && php artisan cache:clear && php artisan config:cache && php artisan route:cache"
